#!/usr/bin/env bash
set -euo pipefail

# ============================================================
# AWS Bootstrap: Create RDS + Cognito + S3 with one command
# Usage: ./aws-bootstrap.sh <project-name> <region> [instance-class]
# Example: ./aws-bootstrap.sh myapp ap-northeast-2
# ============================================================

PROJECT_NAME="${1:?Usage: $0 <project-name> <region> [db-instance-class]}"
AWS_REGION="${2:?Usage: $0 <project-name> <region> [db-instance-class]}"
DB_INSTANCE_CLASS="${3:-db.t4g.micro}"

STACK_NAME="${PROJECT_NAME}-supabase-migration"
TEMPLATE_DIR="$(cd "$(dirname "$0")/../templates" && pwd)"
TEMPLATE_FILE="$TEMPLATE_DIR/aws-stack.yaml"

if [ ! -f "$TEMPLATE_FILE" ]; then
  echo "❌ Template not found: $TEMPLATE_FILE"
  exit 1
fi

# Check AWS credentials
echo "🔑 Checking AWS credentials..."
aws sts get-caller-identity --region "$AWS_REGION" > /dev/null || {
  echo "❌ AWS credentials not configured. Run: aws configure"
  exit 1
}

# Prompt for DB password
echo ""
echo "📝 Enter a master password for PostgreSQL (min 8 chars):"
read -s DB_PASSWORD
echo ""

if [ ${#DB_PASSWORD} -lt 8 ]; then
  echo "❌ Password must be at least 8 characters"
  exit 1
fi

echo "🚀 Creating CloudFormation stack: $STACK_NAME"
echo "   Region: $AWS_REGION"
echo "   Instance: $DB_INSTANCE_CLASS"
echo ""

aws cloudformation create-stack \
  --stack-name "$STACK_NAME" \
  --template-body "file://$TEMPLATE_FILE" \
  --parameters \
    ParameterKey=ProjectName,ParameterValue="$PROJECT_NAME" \
    ParameterKey=DBPassword,ParameterValue="$DB_PASSWORD" \
    ParameterKey=DBInstanceClass,ParameterValue="$DB_INSTANCE_CLASS" \
  --capabilities CAPABILITY_IAM \
  --region "$AWS_REGION"

echo "⏳ Waiting for stack creation (typically 5-10 minutes for RDS)..."
aws cloudformation wait stack-create-complete \
  --stack-name "$STACK_NAME" \
  --region "$AWS_REGION"

echo ""
echo "✅ Stack created successfully!"
echo ""

# Extract outputs
OUTPUTS=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$AWS_REGION" \
  --query 'Stacks[0].Outputs' \
  --output json)

DB_URL=$(echo "$OUTPUTS" | python3 -c "import sys,json; [print(o['OutputValue']) for o in json.load(sys.stdin) if o['OutputKey']=='DatabaseURL']")
DB_HOST=$(echo "$OUTPUTS" | python3 -c "import sys,json; [print(o['OutputValue']) for o in json.load(sys.stdin) if o['OutputKey']=='DatabaseHost']")
POOL_ID=$(echo "$OUTPUTS" | python3 -c "import sys,json; [print(o['OutputValue']) for o in json.load(sys.stdin) if o['OutputKey']=='CognitoUserPoolId']")
CLIENT_ID=$(echo "$OUTPUTS" | python3 -c "import sys,json; [print(o['OutputValue']) for o in json.load(sys.stdin) if o['OutputKey']=='CognitoClientId']")
S3_BUCKET=$(echo "$OUTPUTS" | python3 -c "import sys,json; [print(o['OutputValue']) for o in json.load(sys.stdin) if o['OutputKey']=='S3Bucket']")

# Write .env.aws
ENV_FILE=".env.aws"
cat > "$ENV_FILE" << EOF
# Generated by aws-bootstrap.sh on $(date -u +"%Y-%m-%d %H:%M UTC")
# Merge these into your .env when ready to switch

AWS_RDS_URL=$DB_URL
DATABASE_URL=$DB_URL
AUTH_PROVIDER=cognito
COGNITO_USER_POOL_ID=$POOL_ID
COGNITO_CLIENT_ID=$CLIENT_ID
STORAGE_PROVIDER=s3
AWS_S3_BUCKET=$S3_BUCKET
AWS_REGION=$AWS_REGION
EOF

echo "========================================="
echo "AWS Infrastructure Ready"
echo "========================================="
echo ""
echo "RDS Host:      $DB_HOST"
echo "RDS URL:       $DB_URL"
echo "Cognito Pool:  $POOL_ID"
echo "Cognito Client:$CLIENT_ID"
echo "S3 Bucket:     $S3_BUCKET"
echo ""
echo "📄 Saved to: $ENV_FILE"
echo ""
echo "Next steps:"
echo "  1. Test connection: psql \"$DB_URL\" -c \"SELECT 1\""
echo "  2. Run migration:   Follow SKILL.md Mode 3"
echo ""
echo "⚠️  Security reminder:"
echo "  - RDS is publicly accessible (for migration). Restrict after cutover."
echo "  - S3 CORS allows all origins. Restrict after cutover."
echo "  - DB security group allows 0.0.0.0/0 on 5432. Restrict after cutover."
