AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Supabase-to-AWS migration stack.
  Creates: RDS PostgreSQL (free tier), Cognito User Pool, S3 Bucket.
  User provides: ProjectName, DBPassword, Region.

Parameters:
  ProjectName:
    Type: String
    Description: Project identifier (lowercase, no spaces)
    AllowedPattern: '[a-z0-9-]+'
    ConstraintDescription: Lowercase alphanumeric and hyphens only
  
  DBPassword:
    Type: String
    NoEcho: true
    MinLength: 8
    Description: Master password for PostgreSQL (min 8 chars)
  
  DBInstanceClass:
    Type: String
    Default: db.t4g.micro
    AllowedValues:
      - db.t4g.micro
      - db.t4g.small
      - db.t4g.medium
      - db.r6g.large
    Description: RDS instance size (db.t4g.micro = free tier eligible)

Resources:

  # ==================== VPC (minimal) ====================
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-vpc'

  SubnetA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-subnet-a'

  SubnetB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-subnet-b'

  InternetGateway:
    Type: AWS::EC2::InternetGateway

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref InternetGateway

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  SubnetARouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetA
      RouteTableId: !Ref RouteTable

  SubnetBRouteAssoc:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref SubnetB
      RouteTableId: !Ref RouteTable

  # ==================== RDS ====================
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: !Sub '${ProjectName} DB subnets'
      SubnetIds:
        - !Ref SubnetA
        - !Ref SubnetB

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub '${ProjectName} RDS access'
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp: 0.0.0.0/0  # Restrict in production!

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Sub '${ProjectName}-db'
      Engine: postgres
      EngineVersion: '16.4'
      DBInstanceClass: !Ref DBInstanceClass
      AllocatedStorage: 20
      StorageType: gp3
      MasterUsername: postgres
      MasterUserPassword: !Ref DBPassword
      DBName: !Sub '${ProjectName}'
      PubliclyAccessible: true  # Set false for production
      VPCSecurityGroups:
        - !GetAtt DBSecurityGroup.GroupId
      DBSubnetGroupName: !Ref DBSubnetGroup
      BackupRetentionPeriod: 7
      DeletionProtection: false
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # ==================== Cognito ====================
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ProjectName}-users'
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireUppercase: false
          RequireNumbers: true
          RequireSymbols: false
      Schema:
        - Name: email
          Required: true
          Mutable: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${ProjectName}-app'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED

  # ==================== S3 ====================
  StorageBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-storage-${AWS::AccountId}'
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE]
            AllowedOrigins: ['*']  # Restrict in production!
            MaxAge: 3600
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false

Outputs:
  DatabaseURL:
    Description: PostgreSQL connection string
    Value: !Sub 'postgresql://postgres:${DBPassword}@${Database.Endpoint.Address}:${Database.Endpoint.Port}/${ProjectName}'
  
  DatabaseHost:
    Description: RDS hostname
    Value: !GetAtt Database.Endpoint.Address
  
  CognitoUserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool
  
  CognitoClientId:
    Description: Cognito App Client ID
    Value: !Ref UserPoolClient
  
  S3Bucket:
    Description: Storage bucket name
    Value: !Ref StorageBucket
  
  EnvFile:
    Description: Copy these to your .env
    Value: !Sub |
      DATABASE_URL=postgresql://postgres:${DBPassword}@${Database.Endpoint.Address}:${Database.Endpoint.Port}/${ProjectName}
      AUTH_PROVIDER=cognito
      COGNITO_USER_POOL_ID=${UserPool}
      COGNITO_CLIENT_ID=${UserPoolClient}
      STORAGE_PROVIDER=s3
      AWS_S3_BUCKET=${StorageBucket}
      AWS_REGION=${AWS::Region}
